name: CodSpeed

on:
  push:
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # 3.12 is the minimum reqquired version for profiling enabled
          python-version: "3.12"

      - name: Install the wanted libpq version
        run: sudo ./tools/build/ci_install_libpq.sh

      - name: Install Python packages
        run: pip install ./psycopg[test] ./psycopg_pool ./psycopg_c

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        env:
          PSYCOPG_IMPL: c
          PSYCOPG_TEST_DSN: "host=localhost dbname=postgres user=postgres password=password"
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: pytest tests/benchmarks --codspeed
